name: my_porfolio
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.4
  firebase_core: ^2.25.4
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.15.4
  fluttertoast: ^8.2.4
  web: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/logos/
    - assets/images/

  fonts:
    - family: Diphylleia
      fonts:
        - asset: assets/fonts/Diphylleia/Diphylleia-Regular.ttf
